// File: dff.v
// Generated by MyHDL 0.9.0
// Date: Fri Feb 24 15:21:33 2017


`timescale 1ns/10ps

module dff (
    q,
    d,
    clk
);


output q;
reg q;
input d;
input clk;






always @(posedge clk) begin: DFF_LOGIC
    q <= d;
end

endmodule
