// File: Counter.v
// Generated by MyHDL 0.9.0
// Date: Fri Feb 24 17:24:41 2017


`timescale 1ns/10ps

module Counter (
   output reg [1:0] count,
	input enable,
	input reset
);
// Incrementer on enable.
// 
// count -- output
// enable -- control input, increment when rising edge
// reset -- asynchronous reset input
// n -- counter max value

always @(posedge enable, negedge reset) begin: COUNTER_COUNTERLOGIC
    if (reset == 0) begin
        count <= 0;
    end
    else begin
        count <= count + 1;
    end
end

endmodule
